package de.burnthelemon.ggnadditons.features.HUD;

import java.util.*;

public class TabMessageOfTheDayInputList {

    public static final List<String> customMOTD = new ArrayList<>(Arrays.asList(
            "Welcome to the Blocky Universe!",
            "Craft, Mine, Repeat!",
            "Where every block counts.",
            "Your adventure starts here.",
            "Building dreams one block at a time.",
            "Creeper-free zone (mostly).",
            "Dig deep and find your treasure.",
            "Where the grass is always greener.",
            "Join the pixel party!",
            "Redstone engineers welcome.",
            "Explore the endless possibilities.",
            "Where mobs fear to tread.",
            "Let's get crafting!",
            "Powered by TNT and fun.",
            "PvP? Only if you dare.",
            "Adventure awaits beyond the horizon.",
            "Join the mining frenzy.",
            "Building castles and causing chaos.",
            "Where diamonds shine brighter.",
            "Be brave, the night is dark.",
            "Spawn, craft, survive.",
            "Your base is your kingdom.",
            "Where the creepers won't kill your vibe.",
            "Survival mode: Activated.",
            "Gather resources, conquer worlds.",
            "Build together, survive together.",
            "Let the crafting begin.",
            "Where every day is a new adventure.",
            "From dirt block to diamond pickaxe.",
            "Join the pixel pioneers.",
            "Crafting legends one block at a time.",
            "Where the only limit is your imagination.",
            "Digging up fun daily.",
            "Join the quest for the Ender Dragon.",
            "Noobs welcome, veterans respected.",
            "Where the rivers flow with pixelated water.",
            "Every block tells a story.",
            "A world of infinite possibilities.",
            "Where friendships are built on blocks.",
            "Redstone puzzles and TNT traps.",
            "Your adventure hub.",
            "Let’s build something amazing.",
            "Where survival meets creativity.",
            "Epic builds and epic battles.",
            "Minecraft magic happens here.",
            "Spawn your creativity.",
            "Where the block party never ends.",
            "Digging into fun since day one.",
            "Adventure maps and endless exploration.",
            "Where the night is full of surprises.",
            "Join the community of crafters.",
            "Mining for greatness.",
            "Where every miner has their day.",
            "Surviving the mobs, thriving together.",
            "Building a better block world.",
            "Where the creepers just want to dance.",
            "From cobblestone to castle.",
            "Join the crafting crusade.",
            "Where the trees are pixel perfect.",
            "Dig, craft, explore, survive.",
            "Let’s get blocky!",
            "Where the sun always sets on a pixelated world.",
            "Building bridges, not walls.",
            "Where every night is a new challenge.",
            "Crafting memories one block at a time.",
            "Where the sky is the limit.",
            "Join the builders brigade.",
            "Where every ore has its day.",
            "Pixelated paradise awaits.",
            "Mining, crafting, adventuring—repeat.",
            "Where teamwork makes the dream work.",
            "From survival to adventure.",
            "Building dreams block by block.",
            "Where every pixel counts.",
            "Join the journey to the Nether.",
            "Exploring new horizons daily.",
            "Where every creeper is a potential friend.",
            "Mining for fun, crafting for life.",
            "Where the biomes are diverse and the fun is endless.",
            "Craft your destiny here.",
            "Building blocky wonders.",
            "Where creativity runs wild.",
            "Join the pixelated playground.",
            "From dirt huts to diamond castles.",
            "Where every day is a new build.",
            "Minecraft madness in every block.",
            "Welcome to the world, %p! Explore and make it your own!",
            "Pro tip, %p: A shovel works wonders in the sand!",
            "Did you know, %p? Water can prevent fall damage!",
            "Be careful, %p! Lava is hot enough to melt netherite!",
            "Keep an eye out for rare mobs, %p. They drop special loot!",
            "Got food, %p? Make sure you’re stocked for the journey!",
            "Don’t forget to set your spawn, %p!",
            "Sun’s going down, %p! Get ready for the night!",
            "Tip for survival, %p: Carry a bucket of water for safety!",
            "Psst, %p... Caves often hide treasures!",
            "Use a bed to skip the night, %p!",
            "Look up, %p! The stars have come out tonight.",
            "Teamwork makes the dream work, %p!",
            "Keep exploring, %p. The world is bigger than you think!",
            "Don't dig straight down, %p. That’s the first rule!",
            "Make sure to bring torches, %p! Darkness hides danger.",
            "Is that a spider you hear, %p? Or just your imagination?",
            "Crafting tip, %p: Wool makes beds in any color!",
            "Bring a map, %p! You don’t want to get lost!",
            "Psst... keep a lookout, %p. There's magic in the air.",
            "Stock up on wood, %p! It’s the base of all tools.",
            "Pro tip, %p: Don’t forget your armor!",
            "Lava pools glow, %p. That’s how you find them at night.",
            "Bring food on your adventures, %p! Hunger is real.",
            "It's dangerous to go alone, %p. Take some armor!",
            "Remember, %p: Axes work wonders on wood!",
            "Did you know, %p? Villagers have unique trades!",
            "The deeper you go, %p, the better the loot!",
            "Stay alert, %p! Even the friendliest mobs can surprise.",
            "Build, explore, conquer... Make your story, %p!",
            "Try fishing, %p! You never know what you’ll catch.",
            "Light up your base, %p! Mobs hate the light.",
            "Got a diamond, %p? Save it for an enchantment table!",
            "Stay warm, %p! Winter biomes get chilly.",
            "Climbing mountains, %p? Look out for snow traps!",
            "The Nether awaits, %p. Are you prepared?",
            "Ever tried breeding animals, %p? It’s a tasty investment!",
            "Remember, %p: Gold armor helps in the Nether!",
            "Explore caves carefully, %p. It's easy to get lost.",
            "Exploring the ocean, %p? Keep a door handy for air!",
            "Diamonds await at lower depths, %p.",
            "Check the horizon, %p! A new biome may be nearby.",
            "The night is dark, %p, and full of creepers.",
            "A torch can save your life, %p. Always keep some on you.",
            "The end is near... but is it, %p?",
            "Endermen don’t like eye contact, %p. Look away!",
            "Looking for treasure, %p? Look out for sunken ships.",
            "If you see a cave, %p, you’ve found adventure!",
            "Don't forget, %p: Your sword works faster in the air!",
            "Tip for farmers, %p: Crops grow faster in rows!",
            "Need XP, %p? Try an adventure to find mob spawners!",
            "Want to build high, %p? Scaffolding makes it easy!",
            "Crafting tables are magic, %p. Use them often!",
            "Hearing groans? Zombies could be near, %p!",
            "Fishing at sunrise is peaceful, %p. Give it a try!",
            "Is that a dungeon, %p? Check it out carefully!",
            "Did you know, %p? Netherite doesn't burn in lava.",
            "Potions could be the key to your victory, %p!",
            "The dragon awaits, %p. Prepare for the fight!",
            "Got your elytra, %p? The skies are calling!",
            "Adventure is out there, %p. Go find it!",
            "Looking for emeralds, %p? Villages are a great place!",
            "Try using banners for marking places, %p.",
            "Nether portals link distant places, %p!",
            "Enderman can be friendly, %p. Unless you stare.",
            "The Nether is full of resources, %p. Be brave!",
            "Bring a bow, %p. Ranged weapons can save your life.",
            "Feeling brave, %p? The ocean depths are a challenge!",
            "Horses are great for travel, %p. Find a saddle!",
            "Looking for a cozy spot? Igloos have surprises, %p!",
            "Sometimes, digging up leads to treasure, %p!",
            "Treasure maps guide to hidden loot, %p.",
            "Try exploring new recipes, %p. They might surprise you!",
            "Hunger drains your health, %p. Stay well-fed!",
            "Finding rare biomes is worth the journey, %p!",
            "Village raids bring danger and reward, %p!",
            "Armor makes all the difference, %p. Stay protected.",
            "Mining is profitable, %p. Find those ores!",
            "Snowy mountains are stunning, %p. But watch out for the cold!",
            "Collect rare blocks, %p. They might be valuable!",
            "Caves are dangerous but rewarding, %p!",
            "Crafting takes patience, %p. You’ll get it!",
            "You never know what’s around the corner, %p!",
            "There’s treasure waiting for you, %p. Go find it!"
    ));

    public static Map<Integer, String> getCustomMOTDMap() {
        Map<Integer, String> motdMap = new HashMap<>();
        for (int i = 0; i < customMOTD.size(); i++) {
            motdMap.put(i + 1, customMOTD.get(i));
        }
        return motdMap;
    }
}
