package de.burnthelemon.ggnadditons.features.HUD;

import java.util.*;

public class TabMessageOfTheDayInputList {

    public static final List<String> customMOTD = new ArrayList<>(Arrays.asList(
            "Welcome to the Blocky Universe!",
            "Craft, Mine, Repeat!",
            "Where every block counts.",
            "Your adventure starts here.",
            "Building dreams one block at a time.",
            "Creeper-free zone (mostly).",
            "Dig deep and find your treasure.",
            "Where the grass is always greener.",
            "Join the pixel party!",
            "Redstone engineers welcome.",
            "Explore the endless possibilities.",
            "Where mobs fear to tread.",
            "Let's get crafting!",
            "Powered by TNT and fun.",
            "PvP? Only if you dare.",
            "Adventure awaits beyond the horizon.",
            "Join the mining frenzy.",
            "Building castles and causing chaos.",
            "Where diamonds shine brighter.",
            "Be brave, the night is dark.",
            "Spawn, craft, survive.",
            "Your base is your kingdom.",
            "Where the creepers won't kill your vibe.",
            "Survival mode: Activated.",
            "Gather resources, conquer worlds.",
            "Build together, survive together.",
            "Let the crafting begin.",
            "Where every day is a new adventure.",
            "From dirt block to diamond pickaxe.",
            "Join the pixel pioneers.",
            "Crafting legends one block at a time.",
            "Where the only limit is your imagination.",
            "Digging up fun daily.",
            "Join the quest for the Ender Dragon.",
            "Noobs welcome, veterans respected.",
            "Where the rivers flow with pixelated water.",
            "Every block tells a story.",
            "A world of infinite possibilities.",
            "Where friendships are built on blocks.",
            "Redstone puzzles and TNT traps.",
            "Your adventure hub.",
            "Let’s build something amazing.",
            "Where survival meets creativity.",
            "Epic builds and epic battles.",
            "Minecraft magic happens here.",
            "Spawn your creativity.",
            "Where the block party never ends.",
            "Digging into fun since day one.",
            "Adventure maps and endless exploration.",
            "Where the night is full of surprises.",
            "Join the community of crafters.",
            "Mining for greatness.",
            "Where every miner has their day.",
            "Surviving the mobs, thriving together.",
            "Building a better block world.",
            "Where the creepers just want to dance.",
            "From cobblestone to castle.",
            "Join the crafting crusade.",
            "Where the trees are pixel perfect.",
            "Dig, craft, explore, survive.",
            "Let’s get blocky!",
            "Where the sun always sets on a pixelated world.",
            "Building bridges, not walls.",
            "Where every night is a new challenge.",
            "Crafting memories one block at a time.",
            "Where the sky is the limit.",
            "Join the builders brigade.",
            "Where every ore has its day.",
            "Pixelated paradise awaits.",
            "Mining, crafting, adventuring—repeat.",
            "Where teamwork makes the dream work.",
            "From survival to adventure.",
            "Building dreams block by block.",
            "Where every pixel counts.",
            "Join the journey to the Nether.",
            "Exploring new horizons daily.",
            "Where every creeper is a potential friend.",
            "Mining for fun, crafting for life.",
            "Where the biomes are diverse and the fun is endless.",
            "Craft your destiny here.",
            "Building blocky wonders.",
            "Where creativity runs wild.",
            "Join the pixelated playground.",
            "From dirt huts to diamond castles.",
            "Where every day is a new build.",
            "Minecraft madness in every block.",
            "Welcome to the world, %p! Explore and make it your own!",
            "Pro tip, %p: A shovel works wonders in the sand!",
            "Did you know, %p? Water can prevent fall damage!",
            "Be careful, %p! Lava is hot enough to melt netherite!",
            "Keep an eye out for rare mobs, %p. They drop special loot!",
            "Got food, %p? Make sure you’re stocked for the journey!",
            "Don’t forget to set your spawn, %p!",
            "Sun’s going down, %p! Get ready for the night!",
            "Tip for survival, %p: Carry a bucket of water for safety!",
            "Psst, %p... Caves often hide treasures!",
            "Use a bed to skip the night, %p!",
            "Look up, %p! The stars have come out tonight.",
            "Teamwork makes the dream work, %p!",
            "Keep exploring, %p. The world is bigger than you think!",
            "Don't dig straight down, %p. That’s the first rule!",
            "Make sure to bring torches, %p! Darkness hides danger.",
            "Is that a spider you hear, %p? Or just your imagination?",
            "Crafting tip, %p: Wool makes beds in any color!",
            "Bring a map, %p! You don’t want to get lost!",
            "Psst... keep a lookout, %p. There's magic in the air.",
            "Stock up on wood, %p! It’s the base of all tools.",
            "Pro tip, %p: Don’t forget your armor!",
            "Lava pools glow, %p. That’s how you find them at night.",
            "Bring food on your adventures, %p! Hunger is real.",
            "It's dangerous to go alone, %p. Take some armor!",
            "Remember, %p: Axes work wonders on wood!",
            "Did you know, %p? Villagers have unique trades!",
            "The deeper you go, %p, the better the loot!",
            "Stay alert, %p! Even the friendliest mobs can surprise.",
            "Build, explore, conquer... Make your story, %p!",
            "Try fishing, %p! You never know what you’ll catch.",
            "Light up your base, %p! Mobs hate the light.",
            "Got a diamond, %p? Save it for an enchantment table!",
            "Stay warm, %p! Winter biomes get chilly.",
            "Climbing mountains, %p? Look out for snow traps!",
            "The Nether awaits, %p. Are you prepared?",
            "Ever tried breeding animals, %p? It’s a tasty investment!",
            "Remember, %p: Gold armor helps in the Nether!",
            "Explore caves carefully, %p. It's easy to get lost.",
            "Exploring the ocean, %p? Keep a door handy for air!",
            "Diamonds await at lower depths, %p.",
            "Check the horizon, %p! A new biome may be nearby.",
            "The night is dark, %p, and full of creepers.",
            "A torch can save your life, %p. Always keep some on you.",
            "The end is near... but is it, %p?",
            "Endermen don’t like eye contact, %p. Look away!",
            "Looking for treasure, %p? Look out for sunken ships.",
            "If you see a cave, %p, you’ve found adventure!",
            "Don't forget, %p: Your sword works faster in the air!",
            "Tip for farmers, %p: Crops grow faster in rows!",
            "Need XP, %p? Try an adventure to find mob spawners!",
            "Want to build high, %p? Scaffolding makes it easy!",
            "Crafting tables are magic, %p. Use them often!",
            "Hearing groans? Zombies could be near, %p!",
            "Fishing at sunrise is peaceful, %p. Give it a try!",
            "Is that a dungeon, %p? Check it out carefully!",
            "Did you know, %p? Netherite doesn't burn in lava.",
            "Potions could be the key to your victory, %p!",
            "The dragon awaits, %p. Prepare for the fight!",
            "Got your elytra, %p? The skies are calling!",
            "Adventure is out there, %p. Go find it!",
            "Looking for emeralds, %p? Villages are a great place!",
            "Try using banners for marking places, %p.",
            "Nether portals link distant places, %p!",
            "Enderman can be friendly, %p. Unless you stare.",
            "The Nether is full of resources, %p. Be brave!",
            "Bring a bow, %p. Ranged weapons can save your life.",
            "Feeling brave, %p? The ocean depths are a challenge!",
            "Horses are great for travel, %p. Find a saddle!",
            "Looking for a cozy spot? Igloos have surprises, %p!",
            "Sometimes, digging up leads to treasure, %p!",
            "Treasure maps guide to hidden loot, %p.",
            "Try exploring new recipes, %p. They might surprise you!",
            "Hunger drains your health, %p. Stay well-fed!",
            "Finding rare biomes is worth the journey, %p!",
            "Village raids bring danger and reward, %p!",
            "Armor makes all the difference, %p. Stay protected.",
            "Mining is profitable, %p. Find those ores!",
            "Got an enchanted bow? Range attacks work wonders, %p!",
            "Every block tells a story, %p. Build yours!",
            "Strongholds hold mysteries and portals, %p!",
            "Save up on ender pearls, %p. They’re super useful!",
            "Underwater ruins are beautiful, %p. Explore safely.",
            "Have fun with redstone, %p! It’s electrifying!",
            "Honey blocks have unique uses, %p. Experiment with them!",
            "A wolf companion makes travels easier, %p!",
            "Make a compass, %p! It points to your bed spawn.",
            "Winter biomes have their own beauty, %p!",
            "Travel on ice with a boat, %p. It’s super fast!",
            "Stay hydrated, %p! Oceans are vast and mysterious.",
            "Remember, %p: Only sleep at night.",
            "A horse in diamond armor is a knightly sight, %p!",
            "Careful near ravines, %p. They’re both deep and dark.",
            "The stronghold is hidden, %p. It’s an adventure to find.",
            "Adventure often, %p. The world is filled with secrets.",
            "Finding tridents is rare, %p. Drowned mobs sometimes hold them.",
            "Bookshelves make enchanting stronger, %p.",
            "Axes break shields, %p. Use them wisely in combat!",
            "Armor makes you stronger, %p. Don’t go without it!",
            "Villagers trade unique items, %p. Check often!",
            "Plant trees, %p! They provide wood and oxygen!",
            "Don’t forget a shield, %p. It blocks damage!",
            "Music discs can be found in dungeons, %p. Collect them all!",
            "Found a bastion, %p? It’s dangerous but rewarding.",
            "The end has more than just the dragon, %p!",
            "Trading with villagers is profitable, %p!",
            "The Nether fortress holds secrets, %p.",
            "Beware of cliffs, %p. Falling is costly.",
            "Got a dog or cat? They make excellent companions, %p!",
            "Sand and gravel can fall, %p. Dig safely.",
            "Exploring mineshafts can be lucrative, %p.",
            "Did you know? Gold mines faster with a gold pickaxe, %p!",
            "Boats are lifesavers, %p! Use them on water journeys.",
            "Armor helps in fights, %p. Keep it repaired.",
            "Enchantments change everything, %p. Give them a try!",
            "Collect honey, %p! It has sweet properties.",
            "Turtles lay eggs on beaches, %p. Protect them!",
            "Have you tried shield bashing, %p? It’s handy!",
            "Dragons are real, %p. And they’re epic!",
            "FACT! You died %st_deaths times.",
            "FACT! You killed %st_pkills players.",
            "FACT! You killed %st_mkills mobs.",
            "FACT! You have died %st_timesincedeath ticks ago.",
            "01. He struck his first stone with a pickaxe and knew his journey had begun.",
            "02. Deep in the cave, he found veins of iron, and his heart raced at the discovery.",
            "03. The sound of dripping water echoed as he mined precious coal for torches.",
            "04. A glint of blue in the darkness—a diamond was waiting for him.",
            "05. He unearthed redstone, and ideas for inventions began swirling in his mind.",
            "06. Gravel fell from above, nearly trapping him, but he dug his way to safety.",
            "07. In a narrow passage, he uncovered emeralds, the rare gem of the mountains.",
            "08. Lava threatened his path, but he used water to cool it, creating a safe route.",
            "09. His pickaxe broke, but with a new one, he pressed further into the depths.",
            "10. The caverns grew quiet, and he sensed he had taken all the treasures it held.",
            "11. He stepped through the portal, flames crackling around him.",
            "12. Ghasts floated above, their cries echoing through the fiery landscape.",
            "13. Fortress walls loomed, and he battled blazes for their precious rods.",
            "14. Nether wart lined the fortress halls, a strange plant of dark magic.",
            "15. A magma cube jumped out, nearly knocking him into a pool of lava.",
            "16. Piglins eyed him warily until he offered gold, securing a short truce.",
            "17. He braved the basalt deltas, hopping carefully across treacherous terrain.",
            "18. A hoglin charged, but he fought it off, claiming its meat for the journey.",
            "19. Soul sand slowed his steps as he gathered it for future potions.",
            "20. Crimson and warped forests glowed, and he felt the Nether’s true beauty.",
            "21. Back in the Overworld, he roamed new biomes, each more beautiful than the last.",
            "22. He found a village where he traded with curious, nodding villagers.",
            "23. An outpost stood on a hill, and he freed an iron golem from its cage.",
            "24. In the distance, a mansion loomed, filled with eerie noises and lurking evokers.",
            "25. He sailed through vast oceans, discovering shipwrecks and sunken ruins.",
            "26. In the desert, a temple revealed hidden treasure beneath the sands.",
            "27. A jungle temple guarded secrets in the undergrowth, and he solved its puzzles.",
            "28. Pillager patrols spotted him, but he escaped their crossbow shots.",
            "29. On mountain peaks, he saw the world below and marveled at its scale.",
            "30. A ruined portal hinted at journeys beyond, its blocks glowing faintly.",
            "31. After gathering Eyes of Ender, he finally found the stronghold’s entrance.",
            "32. He activated the End Portal and felt a strange pull as he stepped through.",
            "33. In the End, the dragon’s roar shook him to his core, but he stood firm.",
            "34. Tower after tower, he destroyed the crystals, weakening the dragon.",
            "35. The dragon lunged at him, but he fired his last arrow, defeating the beast.",
            "36. The Endermen watched in silence as he gathered the dragon’s egg.",
            "37. He built a bridge to the outer islands, his gaze fixed on the horizon.",
            "38. In an end city, he found shulkers and claimed the treasures within.",
            "39. An elytra hung on a ship above, waiting for him to take to the skies.",
            "40. He soared back, his journey through the End finally complete.",
            "41. Back in the Overworld, he discovered an ancient shrine in the mountains.",
            "42. A riddle was carved into stone, guiding him to his next challenge.",
            "43. The trials tested his skills, and he emerged with rare artifacts.",
            "44. While mining deeper, he heard a faint, ominous rumble below.",
            "45. He uncovered the Deep Dark, an ancient city hidden in shadows.",
            "46. Warden’s footsteps echoed as he crept through the city in silence.",
            "47. The city’s secrets beckoned, and he uncovered long-forgotten relics.",
            "48. At the heart of the city, he found a portal unlike any he’d seen before.",
            "49. With a final step, he vanished into the unknown, his tale lost to time."
    ));
}
