package de.burnthelemon.ggnadditons.util;

import java.util.*;

public class TabMODT {

    public static final List<String> customMOTD = new ArrayList<>(Arrays.asList(
            "Welcome to the Blocky Universe!",
            "Craft, Mine, Repeat!",
            "Where every block counts.",
            "Your adventure starts here.",
            "Building dreams one block at a time.",
            "Creeper-free zone (mostly).",
            "Dig deep and find your treasure.",
            "Where the grass is always greener.",
            "Join the pixel party!",
            "Redstone engineers welcome.",
            "Explore the endless possibilities.",
            "Where mobs fear to tread.",
            "Let's get crafting!",
            "Powered by TNT and fun.",
            "PvP? Only if you dare.",
            "Adventure awaits beyond the horizon.",
            "Join the mining frenzy.",
            "Building castles and causing chaos.",
            "Where diamonds shine brighter.",
            "Be brave, the night is dark.",
            "Spawn, craft, survive.",
            "Your base is your kingdom.",
            "Where the creepers won't kill your vibe.",
            "Survival mode: Activated.",
            "Gather resources, conquer worlds.",
            "Build together, survive together.",
            "Let the crafting begin.",
            "Where every day is a new adventure.",
            "From dirt block to diamond pickaxe.",
            "Join the pixel pioneers.",
            "Crafting legends one block at a time.",
            "Where the only limit is your imagination.",
            "Digging up fun daily.",
            "Join the quest for the Ender Dragon.",
            "Noobs welcome, veterans respected.",
            "Where the rivers flow with pixelated water.",
            "Every block tells a story.",
            "A world of infinite possibilities.",
            "Where friendships are built on blocks.",
            "Redstone puzzles and TNT traps.",
            "Your adventure hub.",
            "Let’s build something amazing.",
            "Where survival meets creativity.",
            "Epic builds and epic battles.",
            "Minecraft magic happens here.",
            "Spawn your creativity.",
            "Where the block party never ends.",
            "Digging into fun since day one.",
            "Adventure maps and endless exploration.",
            "Where the night is full of surprises.",
            "Join the community of crafters.",
            "Mining for greatness.",
            "Where every miner has their day.",
            "Surviving the mobs, thriving together.",
            "Building a better block world.",
            "Where the creepers just want to dance.",
            "From cobblestone to castle.",
            "Join the crafting crusade.",
            "Where the trees are pixel perfect.",
            "Dig, craft, explore, survive.",
            "Let’s get blocky!",
            "Where the sun always sets on a pixelated world.",
            "Building bridges, not walls.",
            "Where every night is a new challenge.",
            "Crafting memories one block at a time.",
            "Where the sky is the limit.",
            "Join the builders brigade.",
            "Where every ore has its day.",
            "Pixelated paradise awaits.",
            "Mining, crafting, adventuring—repeat.",
            "Where teamwork makes the dream work.",
            "From survival to adventure.",
            "Building dreams block by block.",
            "Where every pixel counts.",
            "Join the journey to the Nether.",
            "Exploring new horizons daily.",
            "Where every creeper is a potential friend.",
            "Mining for fun, crafting for life.",
            "Where the biomes are diverse and the fun is endless.",
            "Craft your destiny here.",
            "Building blocky wonders.",
            "Where creativity runs wild.",
            "Join the pixelated playground.",
            "From dirt huts to diamond castles.",
            "Where every day is a new build.",
            "Minecraft madness in every block."
    ));
}
